version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: "cron"
      cronjob: "0 0 5,20 * *"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 0
    groups:
      ruby-security:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "cron"
      cronjob: "0 0 5,20 * *"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 0
    groups:
      actions-security:
        applies-to: security-updates
        patterns: ["*"]